### ISSUE TITLE
Update module to reflect new state-home directory

### ISSUE THREAD

**Issue by sdondley** [jonathanstowe/XDG-BaseDirectory#4]
According to this [blog post ](https://www.ctrl.blog/entry/xdg-basedir-scripting.html), the XDG base directory specification was recently updated (end of last summer) to add a new directory for state which appears in `$HOME/.local/share`.

I wil try to update the module to reflect this new requirement.

**Comment by jonathanstowe** [comment]
Looks good, cheers for the PR.
